version: "3.8"

services:
  back:
    build: ./back
    container_name: transcription-back
    ports:
      - "4000:4000"
    depends_on:
      - minio
    environment:
      - BACK_PORT=${BACK_PORT}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET=${MINIO_BUCKET}
      - S3_BUCKET=${S3_BUCKET}
    volumes:
      - ./back:/usr/src/app

  front:
    build: ./front
    container_name: transcription-front
    ports:
      - "3000:3000"
    depends_on:
      - back
    environment:
      - VITE_API_URL=${VITE_API_URL}
    volumes:
      - ./front:/usr/src/app

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9090"

  createbucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      mc mb local/${MINIO_BUCKET};
      mc policy set public local/${MINIO_BUCKET};
      exit 0;
      "

volumes:
  minio-data:
